debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.fatcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: kkh2415
    password: kkh2415
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated #@Repository 애노테이션을 붙은 레포지토리만 api로 노출

#---
#
#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
#  test.database.replace: none #모든 테스트를 testdb에서 설정한 DB에서 실행
